### ISSUE TITLE
백엔드 API 템플릿 구현

### ISSUE THREAD

**Issue by woochul2** [woowa-techcamp-2022/web-moneybook-5#12]
# 💼 TASK 개요 

[API 명세](https://github.com/woowa-techcamp-2022/web-moneybook-5/wiki/API-%EB%AA%85%EC%84%B8)에 맞게 라우터 엔드포인트 설정

# ✅ TODO 및 진행현황 

- [x] GET /api/history
- [x] POST /api/history
- [x] DELETE /api/history/:id
- [x] PATCH /api/history/:id
- [x] GET /api/recentHistory
- [x] GET /api/paymentMethod
- [x] POST /api/paymentMethod
- [x] DELETE /api/paymentMethod/:id

# ⏰ 예상 소요 시간

1h 30m

<!-- 정확하지 않아도 좋으나 점점 구체화하면 좋을 것 같습니다. 데이터 쌓기 ->
