### ISSUE TITLE
거래내역 리스트 컴포넌트 기능 구현

### ISSUE THREAD

**Issue by ja960508** [woowa-techcamp-2022/web-moneybook-5#14]
# 💼 TASK 개요 
거래내역 컴포넌트의 필터 이벤트 및 state 필터링을 구현한다.

# ✅ TODO 및 진행현황 
- [x] 거래내역 리스트 헤더의 필터 버튼 클릭 시 필터 state를 변경하고 리렌더링한다.
- [x] 컴포넌트의 템플릿 메소드에서 history를 state에 따라 필터링하고 html을 생성한다.
    - [x] 마크업 시 전체 내역은 현재 필터된 history의 길이를 렌더링한다.

# ⏰ 예상 소요 시간
45m
<!-- 정확하지 않아도 좋으나 점점 구체화하면 좋을 것 같습니다. 데이터 쌓기 ->
