### ISSUE TITLE
통계 컴포넌트 원형 차트 렌더링

### ISSUE THREAD

**Issue by ja960508** [woowa-techcamp-2022/web-moneybook-5#17]
# 💼 TASK 개요 
통계 컴포넌트의 차트 섹션을 렌더링한다.

# ✅ TODO 및 진행현황 
- [x] 현재 월의 카테고리 별 지출 총액을 리스트 형태로 나타낸다.
- [x] 리스트의 내역은 총액이 큰 순서대로 정렬한다.
- [x] 지출 총액 리스트를 기반으로 원형 차트를 그린다. (색상은 카테고리와 동일하게 한다.)

# ⏰ 예상 소요 시간
3h
<!-- 정확하지 않아도 좋으나 점점 구체화하면 좋을 것 같습니다. 데이터 쌓기 ->
