### ISSUE TITLE
통계 컴포넌트 월별 소비 추이, 그래프 상세내역

### ISSUE THREAD

**Issue by ja960508** [woowa-techcamp-2022/web-moneybook-5#18]
# 💼 TASK 개요 
통계 컴포넌트의 카테고리 클릭 시 월별 소비 추이와 현재 월을 해당 카테고리 내역들을 보여준다.

# ✅ TODO 및 진행현황 
- [ ] 카테고리 클릭 시 최근 6개월 간의 해당 카테고리의 지출 내역을 요청한다.
- [ ] 불러온 데이터를 기반으로 그래프를 그린다.
- [ ] 그래프의 아래 쪽에 현재 월의 해당 카테고리 지출 내역들을 렌더링한다.
    - [ ] 메인 페이지와 다르게 오른쪽 상단의 지출 총액은 나타나지 않는다.

# ⏰ 예상 소요 시간
2h

<!-- 정확하지 않아도 좋으나 점점 구체화하면 좋을 것 같습니다. 데이터 쌓기 ->
