### ISSUE TITLE
SPA 라우터 구현

### ISSUE THREAD

**Issue by woochul2** [woowa-techcamp-2022/web-moneybook-5#23]
# 💼 TASK 개요 

브라우저 URL로 바로 접근했을 때도 렌더링이 되도록 SPA 라우터를 구현합니다.

# ✅ TODO 및 진행현황 

- [ ] URL로 바로 접근했을 때 렌더링 테스트
- [ ] 새로고침 시 렌더링 테스트
- [ ] 뒤로가기, 앞으로가기 시 렌더링 테스트

# ⏰ 예상 소요 시간

1h

<!-- 정확하지 않아도 좋으나 점점 구체화하면 좋을 것 같습니다. 데이터 쌓기 ->
