### ISSUE TITLE
거래내역 컴포넌트 수정, 삭제 기능 구현

### ISSUE THREAD

**Issue by ja960508** [woowa-techcamp-2022/web-moneybook-5#27]
# 💼 TASK 개요 
거래내역 컴포넌트와 관련된 이벤트 기능을 구현한다.

# ✅ TODO 및 진행현황 
- [x] 거래내역 호버 시 삭제 버튼이 보여진다.
    - [x] 삭제 버튼 클릭 시 삭제 여부를 묻는 모달 창이 나타난다.
    - [x] 삭제 버튼 확인 시 서버로 삭제 요청을 보내고 삭제 액션을 dispatch 한다.
- [x] 거래내역 컴포넌트를 클릭 시 수정 액션을 dispatch 한다.
    - [x] 수정 액션은 수정 폼의 input들을 채운다.
- [x] history__item hover 색상 변경

# ⏰ 예상 소요 시간
1h 30m
<!-- 정확하지 않아도 좋으나 점점 구체화하면 좋을 것 같습니다. 데이터 쌓기 ->
