### ISSUE TITLE
결제 수단이 삭제되면 기존 거래내역의 결제 수단을 빈칸으로 바꾸기

### ISSUE THREAD

**Issue by woochul2** [woowa-techcamp-2022/web-moneybook-5#44]
# 💼 TASK 개요 

결제 수단이 삭제돼도 거래 내역의 결제 수단이 유지되는 기존 방식에서 빈칸으로 없애는 방식으로 수정하기

# ✅ TODO 및 진행현황 

- [x] DB의 history에서 해당하는 결제 수단을 삭제
- [x] 화면에서 결제 수단 filter
- [x] 기존에 있는 결제수단과 동일한 결제수단을 추가하려고 하면 막아주기

# ⏰ 예상 소요 시간

1h 30m

<!-- 정확하지 않아도 좋으나 점점 구체화하면 좋을 것 같습니다. 데이터 쌓기 ->
