### ISSUE TITLE
통계 페이지 하단 리스트 렌더링

### ISSUE THREAD

**Issue by ja960508** [woowa-techcamp-2022/web-moneybook-5#49]
# 💼 TASK 개요 
통계 페이지 하단 이번 달과 클릭한 카테고리에 맞는 거래내역들을 출력한다.

# ✅ TODO 및 진행현황 
- [x] 통계 페이지 컴포넌트의 리스트 부분을 재사용 가능하게 컴포넌트로 분리한다.
- [x] 통계 페이지 하단에 리스트를 출력한다.
    - [x] 메인 페이지와는 다르게 각 날짜의 총합은 출력하지 않는다.

# ⏰ 예상 소요 시간
2h

<!-- 정확하지 않아도 좋으나 점점 구체화하면 좋을 것 같습니다. 데이터 쌓기 ->
