### ISSUE TITLE
수입, 지출 폼의 +, - 폼에 따라 카테고리가 필터링 되도록 수정

### ISSUE THREAD

**Issue by woochul2** [woowa-techcamp-2022/web-moneybook-5#50]
# ✅ TODO 및 진행현황 

- [x] 수입, 지출 폼의 +, - 폼에 따라 카테고리 필터링
- [x] 이미 카테고리가 선택된 상태에서 +, - 버튼을 누르면 선택한 카테고리 초기화
- [x] 드롭다운 엘리먼트 호버 시 border-radius가 초과되지 않도록 수정

# ⏰ 예상 소요 시간

1h

<!-- 정확하지 않아도 좋으나 점점 구체화하면 좋을 것 같습니다. 데이터 쌓기 ->
