### ISSUE TITLE
수입 지출 내역 입력 폼 디자인, 마크업, 입력 구현

### ISSUE THREAD

**Issue by woochul2** [woowa-techcamp-2022/web-moneybook-5#8]
# 💼 TASK 개요 

수입 지출 내역 입력 폼 기능, 디자인을 구현한다.

# ✅ TODO 및 진행현황 

- [x] 수입 지출 내역 마크업
- [x] 수입 지출 내역 디자인
- [x] 내용 input은 30자를 초과할 수 없다
- [x] 분류 클릭 시 드롭다운 출력
- [x] 결제 수단 클릭 시 드롭다운 출력
- [x] 금액 Input 안의 빼기(-) 버튼을 누르면 더하기(+)로 토글
- [x] 일자 입력 시 자동으로 마침표(.) 추가(정규 표현식)
- [x] 금액 입력 시 자동으로 콤마(,) 추가(toLocalString)
- [x] 모든 input을 입력해야 제출 버튼 활성화

# ⏰ 예상 소요 시간

2h 30m

<!-- 정확하지 않아도 좋으나 점점 구체화하면 좋을 것 같습니다. 데이터 쌓기 ->
