### ISSUE TITLE
결제 수단 추가, 삭제 폼 모달

### ISSUE THREAD

**Issue by woochul2** [woowa-techcamp-2022/web-moneybook-5#9]
# 💼 TASK 개요 

결제 수단 추가, 삭제 폼 모달 디자인, 마크업, 기능 구현

# ✅ TODO 및 진행현황 

- [x] 결제 수단 x 버튼 클릭 시 삭제 모달 열기
- [x] 결제 수단 추가 버튼 클릭 시 추가 모달 열기
- [x] 결제 수단 추가 시 Input이 있어야 등록 버튼 활성화
- [x] 결제 수단 추가 input은 10자를 초과할 수 없다.
- [x] 모달 취소 버튼 또는 바깥 클릭 시 모달 닫기
- [x] 추가 또는 삭제 시 결제 수단 state 변경
    - [x] 각 항목에 맞는 수정, 삭제 요청

# ⏰ 예상 소요 시간

1h 30m

<!-- 정확하지 않아도 좋으나 점점 구체화하면 좋을 것 같습니다. 데이터 쌓기 ->
